### PR TITLE
Create PopularHackingToolsImage.md

### PR DESCRIPTION
**Pull request by Jessie-Park**
An infographic of different hacking tools used and bullet points about each tool with a small description.

### CODE REVIEW

**Comment by cvoges12** [comment]
Why did you make another location for IT?

**Comment by cvoges12** [comment]
Did you try looking at the tree before adding a new directory?

**Comment by Jessie-Park** [comment]
Ah I see, I've found it in the sciences > Applied section. Should I create an InformationSecurity directory?

**Comment by Jessie-Park** [comment]
Edited location to Science/Applied/ComputerTechnology/InformationSecurity/PopularHackingToolsImage.md

**Comment by cvoges12** [comment]
Why not put information security under information technology?

**Comment by Jessie-Park** [comment]
Good idea, I've moved it to the IT dir

**Comment by cvoges12** [comment]
Alright, looks good.

**Pull request merged**
