### PR TITLE
added to linear algebra section

### PR DESCRIPTION
**Pull request by clbeggs**
Added to the linear algebra README, still have things to do. Basic rough draft.

### CODE REVIEW

**Comment by cvoges12** [comment]
`<script src="//yihui.org/js/math-code.js"></script> <script async src="//mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML"> </script>`
This line and some LaTeX like things are broken. Please use stardard markdown for README. Thanks for your contributions.

**Comment by cvoges12** [comment]
Also, keep the existing links as `[foo](url)` format instead of `foo: [](url)`. I'd rather embed the links straight into the text.

**Comment by clbeggs** [comment]
There we go. Should have fixed all the latex issues, but could still use some formatting. 

For future reference, I used this website:
https://www.codecogs.com/latex/eqneditor.php

To render the latex equations to html to put in the readme.

**Comment by Jessie-Park** [comment]
Everything is looking really good! The only change I'd like to make is that instead of direct URLs in the md file, can you switch them to the `[foo](url)` format? For example:

`MIT course: https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/ Great intro to linear algebra. Should be very similar to any undergraduate course taken at a college.`

Could be turned into something like this:

`[MIT Open Courseware](https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/) is a great intro to linear algebra.`

[MIT Open Courseware](https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/) is a great intro to linear algebra.

**Comment by clbeggs** [comment]
Should have everything fixed.

**Pull request merged**
